### PR TITLE
Implement random colorize

### PR DESCRIPTION
**Pull request by mashiro**

### CODE REVIEW

**Comment by dayflower** [comment]
Your logic looks good to me, but I guess not everyone (including me) wants to use this feature.

Could you add a flag to the configuration to enable this feature?

How about this?
```yaml
color:
  random:
    apply:
      - channel
      - user
    rejects:
      - black
      - darkblue
```

**Comment by mashiro** [comment]
It's looks good. OK, I'll try this.

**Comment by mashiro** [comment]
Switchable with channel, user and mention.

**Comment by dayflower** [comment]
Fine!

Thanks for your contribution!

**Pull request merged**
